default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 1234

development:
  <<: *default
  database: mystore_development
 

test:
  <<: *default
  database: mystore_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
